language: d

sudo: false

d:
  - dmd
  - dmd-2.078.3
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.2
  - ldc
  - ldc-1.7.0
  - ldc-1.0.0
  - ldc-0.17.0
  - ldc-0.16.1
  - ldc-0.15.1
  - ldc-0.14.0
  - gdc
  - gdc-4.9.3
  - gdc-4.9.0

script:
  - dub test --compiler=$DC || exit 1
